title: vpnsell
description: 'git@github.com:MicrosoftDocs/memdocs.git'
template:
  repo: vpnsell-template
  name: vpnsell
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
